sudo: required
language: node_js

services:
  - docker
node_js:
  - "6.10.0"
# " && node ./seed/seed.js && ./node_modules/mocha/bin/mocha ./tests/accept/*.js --timeout 15000"
before_install:
  - docker pull mongo
  - docker run -d -p 127.0.0.1:27017:27017 mongo
  - docker ps -a
install:
  - npm install
before_script:
  - npm run seed